### ISSUE TITLE
[추가] 사이드바 클릭 관련 기능

### ISSUE THREAD

**Issue by seungcar** [parkwoohyeok/happy15team#10]
## 💡 Feature Issue
사이드바 클릭 관련 기능

## 🌿  To-do
- [x] 로고 클릭시 "/"로 이동
- [x] 플러스 아이콘 클릭시 모달창뜨기위한 밑작업
- [x] 대쉬보드 마우스 올리거나 클릭시 배경색 변경
- [x] 대쉬보드 리스트 컴포넌트로 분리
