### ISSUE TITLE
[추가] "대시보드 생성" 모달 열고 닫는 기능과 UI

### ISSUE THREAD

**Issue by seungcar** [parkwoohyeok/happy15team#15]
## 💡 Feature Issue
"대시보드 생성" 모달 열고 닫는 기능과 UI 만들기

## 🌿  To-do
- [x] 사이드바의 + 버튼 누르면 index로 props 전달해서 모달 열기
- [x] 모달 외부를 클릭하거나 모달의 취소 버튼 누르면 모달 닫기
- [x] 모달 폼 만들기
- [x] 모달 색깔 선택하는 원들 컬러값들 임시데이터줘서 생성
- [x] 모달 폼 UI
